name: mindspa_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.3.3
  flutter_svg: ^1.0.2
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  introduction_screen: ^2.1.0
  logger: ^1.1.0
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/png/Mind-Spa_the_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
